// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "NativeGameplayTags.h"

namespace MortisGameplayTags
{
	// ====================		Input Tags		====================
	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Zoom);
	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Interact);

	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Select_Left);
	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Select_Right);

	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Hold);

	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Hold_Ability_Sprint);
	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Ability_Roll);

	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Ability_LightAttack);
	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Ability_WeaponSkill);

	// ====================		Ability Tags	====================	
	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Sprint);
	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Roll);

	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_EquipWeapon);
	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_UnequipWeapon);

	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Attack_Light);
	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Attack_WeaponSkill);

	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Action_Attack_Melee);
	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Action_Attack_Ranged);
	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Action_Attack_Pattern);
	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Action_Turn);
	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Action_HitReact);
	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Action_Stagger);
	
	// ====================		State Tags		====================
	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Dead);

	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Action_Attacking);
	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Action_Turning);
	
	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Movement_Idle);
	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Movement_Strafing);
	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Movement_Chasing);

	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Combat_Guarding);

	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Enemy_Phase_1);
	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Enemy_Phase_2);
	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Enemy_Phase_3);
	
	// ====================		Event Tags		====================
	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Player_SwitchWeapon);
	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Player_Complete_Roll);
	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Player_Success_LightAttack);
	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Player_Success_SkillAttack);
	
	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Action_ExecutePattern);
	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Action_Turn);
	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Action_HitReact);
	
	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_RuneSet_Slash_Exaltation_Done);

	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Combat_AttackHit);
	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Combat_Combo_Next);
	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Combat_Attack_Blocked);
	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Combat_Block_Success);
	
	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Montage_EndWarpUpdate);

	// ====================		Data Tags		====================
	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Weapon_DefaultSword);
	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Weapon_FallenKnightSword);
	
	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Shield);

	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_CollisionType_Weapon_Normal);
	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_CollisionType_Weapon_Special);
	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_CollisionType_Shield);

	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_AttackType_Pierce);
	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_AttackType_Blunt);
	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_AttackType_Slash);
	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_AttackType_Magic);
	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_AttackScale);
	
	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Stat_PoiseDamage);
	

	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_RuneValue);
	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Cost_Health);
	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Cost_Stamina);
	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Cost_Mana);

	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Player_Stat_MaxHP);
	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Player_Stat_MaxStamina);
	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Player_Stat_StaminaRegen);
	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Player_Stat_StaminaReductionRate);
	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Player_Stat_MaxMana);
	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Player_Stat_ManaRegen);
	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Player_Stat_ManaReductionRate);

	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Player_Stat_Strength);
	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Player_Stat_Dexterity);
	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Player_Stat_Intelligence);

	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Player_Stat_WeaponDamage);
	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Player_Stat_Coefficient_Strength);
	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Player_Stat_Coefficient_Dexterity);
	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Player_Stat_Coefficient_Intelligence);

	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Player_Stat_BonusDamage_Percent_All);
	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Player_Stat_BonusDamage_Percent_Pierce);
	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Player_Stat_BonusDamage_Percent_Blunt);
	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Player_Stat_BonusDamage_Percent_Slash);
	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Player_Stat_BonusDamage_Percent_Magic);

	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Player_Stat_Speed_LightAttack);
	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Player_Stat_Speed_WeaponSkill);
	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Player_Stat_Speed_Move);

	// ====================		RuneSet Tags	====================
	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Rune_Set_Slashing);
	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Rune_Set_Piercing);
	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Rune_Set_Combo);
	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Rune_Set_Mystery);
	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Rune_Set_Inspiration);

	ETERNALMORTIS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Enemy_Stat_WeaponDamage);

	// ====================		Character Tags	====================

}
