;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Data.Weapon.DarkIronGreatsword",NewTagName="Data.Weapon.2H.DarkIronGreatsword")
+GameplayTagList=(Tag="Data.Weapon.2H.DarkIronGreatsword",DevComment="")
+GameplayTagList=(Tag="Data.Weapon.BarbedWarclub",DevComment="")
+GameplayTagList=(Tag="Data.Weapon.DragonSlayer",DevComment="")
+GameplayTagList=(Tag="Data.Weapon.Duskfang",DevComment="")
+GameplayTagList=(Tag="Data.Weapon.EclipseBrand",DevComment="")
+GameplayTagList=(Tag="Data.Weapon.GildedRapier",DevComment="")
+GameplayTagList=(Tag="Data.Weapon.Oathcrusher",DevComment="")
+GameplayTagList=(Tag="Data.Weapon.ShardbreakerMaul",DevComment="")
+GameplayTagList=(Tag="Data.Weapon.StoneBound",DevComment="")
+GameplayTagList=(Tag="Data.Weapon.StormscribeBlade",DevComment="")
+GameplayTagList=(Tag="Data.Weapon.WornHexblade",DevComment="")
+GameplayTagList=(Tag="Data.Weapon.WornPointblade",DevComment="")
+GameplayTagList=(Tag="Event.Player.Complete.RightClick",DevComment="")
+GameplayTagList=(Tag="Event.RuneSet.Flow.5Stack",DevComment="")
+GameplayTagList=(Tag="Event.Skill.ResetEnemySet",DevComment="")
+GameplayTagList=(Tag="Experience.Guardian",DevComment="")
+GameplayTagList=(Tag="Experience.Hunter",DevComment="")
+GameplayTagList=(Tag="Experience.Pilgrim",DevComment="")
+GameplayTagList=(Tag="Experience.Sage",DevComment="")
+GameplayTagList=(Tag="Experience.Scholar",DevComment="")
+GameplayTagList=(Tag="Experience.Shopper",DevComment="")
+GameplayTagList=(Tag="Experience.Swordman",DevComment="")
+GameplayTagList=(Tag="Experience.Warrior",DevComment="")

